# Generated by Django 5.2.8 on 2025-12-05 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_stage_lead_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='order_in_stage',
            field=models.IntegerField(default=0),
        ),
    ]
