# Generated by Django 5.2.8 on 2025-12-12 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_lead_order_in_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='win_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
