# Generated by Django 5.2.8 on 2025-12-12 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_add_win_score_cache'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='order_in_stage',
        ),
    ]
