# Generated by Django 5.2.8 on 2025-12-16 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_create_application_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='position',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
