# Generated by Django 5.2.8 on 2025-12-16 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_add_position_to_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interaction',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='customers',
        ),
        migrations.AddField(
            model_name='joboffer',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_offers', to='crm.application'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='offer_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='response_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('negotiating', 'Negotiating')], default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
