# Generated by Django 5.2.8 on 2025-12-16 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_remove_customer_and_add_joboffer_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_offers', to='crm.application'),
        ),
    ]
