# Generated by Django 5.2.8 on 2025-12-16 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_make_joboffer_application_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='offered',
            field=models.CharField(blank=True, help_text='The actual salary/compensation offered', max_length=100),
        ),
    ]
