# Generated by Django 5.2.8 on 2025-12-16 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_add_offered_field_to_joboffer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateField(help_text='Deadline for assessment/project submission')),
                ('website_url', models.URLField(blank=True, help_text='URL for assessment platform or project submission')),
                ('recruiter_contact_name', models.CharField(blank=True, help_text='Recruiter/contact name for submission', max_length=200)),
                ('recruiter_contact_email', models.EmailField(blank=True, help_text='Recruiter/contact email for submission', max_length=254)),
                ('recruiter_contact_phone', models.CharField(blank=True, help_text='Recruiter/contact phone for submission', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the assessment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='crm.application')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['deadline'],
            },
        ),
    ]
