# Generated by Django 5.2.8 on 2025-12-16 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_create_assessment_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interaction',
            name='contact',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
