# Generated by Django 5.2.8 on 2025-12-17 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_remove_contact_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('provider', models.CharField(choices=[('gmail', 'Gmail'), ('outlook', 'Outlook')], max_length=20)),
                ('access_token', models.TextField(blank=True, help_text='OAuth access token (encrypted in production)')),
                ('refresh_token', models.TextField(blank=True, help_text='OAuth refresh token (encrypted in production)')),
                ('token_expires_at', models.DateTimeField(blank=True, help_text='When the access token expires', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether email sync is active')),
                ('last_sync_at', models.DateTimeField(blank=True, help_text='Last successful email sync timestamp', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Account',
                'verbose_name_plural': 'Email Accounts',
                'db_table': 'email_accounts',
            },
        ),
    ]
