# Generated by Django 5.2.8 on 2025-12-17 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_create_email_account_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoDetectedApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_message_id', models.CharField(db_index=True, help_text='Unique email message ID to prevent duplicates', max_length=255)),
                ('company_name', models.CharField(max_length=200)),
                ('position', models.CharField(blank=True, max_length=200)),
                ('where_applied', models.CharField(blank=True, max_length=100)),
                ('confidence_score', models.FloatField(default=0.0, help_text='Confidence score from 0.0 to 1.0')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('merged', 'Merged with Existing')], default='pending', max_length=20)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('email_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detected_applications', to='crm.emailaccount')),
                ('merged_into_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_from_detected', to='crm.application')),
            ],
            options={
                'verbose_name': 'Auto-Detected Application',
                'verbose_name_plural': 'Auto-Detected Applications',
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['email_account', 'status'], name='crm_autodet_email_a_08b971_idx')],
            },
        ),
    ]
