# Generated by Django 5.2.8 on 2025-12-18 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_create_auto_detected_application_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='autodetectedapplication',
            name='applied_date',
            field=models.DateField(blank=True, help_text='Date when application was submitted (extracted from email)', null=True),
        ),
        migrations.AddField(
            model_name='autodetectedapplication',
            name='email',
            field=models.EmailField(blank=True, help_text='Contact email if mentioned in email', max_length=254),
        ),
        migrations.AddField(
            model_name='autodetectedapplication',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number if mentioned in email', max_length=20),
        ),
        migrations.AddField(
            model_name='autodetectedapplication',
            name='salary_range',
            field=models.CharField(blank=True, help_text='Salary range if mentioned in email', max_length=100),
        ),
        migrations.AddField(
            model_name='autodetectedapplication',
            name='stack',
            field=models.TextField(blank=True, help_text='Technology stack mentioned in email'),
        ),
        migrations.AlterField(
            model_name='autodetectedapplication',
            name='where_applied',
            field=models.CharField(blank=True, help_text='Job board or platform where application was submitted', max_length=100),
        ),
    ]
