# Generated by Django 5.2.8 on 2025-12-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_add_fields_to_auto_detected_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autodetectedapplication',
            name='detected_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the application was detected (email date or sync time)'),
        ),
        migrations.AlterField(
            model_name='autodetectedapplication',
            name='where_applied',
            field=models.CharField(blank=True, default='', help_text='Job board or platform where application was submitted', max_length=100),
        ),
    ]
