# Generated by Django 5.2.8 on 2025-12-18 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_alter_autodetectedapplication_detected_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autodetectedapplication',
            name='email',
            field=models.EmailField(blank=True, default='', help_text='Contact email if mentioned in email', max_length=254),
        ),
        migrations.AlterField(
            model_name='autodetectedapplication',
            name='phone_number',
            field=models.CharField(blank=True, default='', help_text='Phone number if mentioned in email', max_length=20),
        ),
        migrations.AlterField(
            model_name='autodetectedapplication',
            name='salary_range',
            field=models.CharField(blank=True, default='', help_text='Salary range if mentioned in email', max_length=100),
        ),
    ]
